export default {
  "login": "Perin-Mangukiya",
  "id": 79306200,
  "node_id": "MDQ6VXNlcjc5MzA2MjAw",
  "avatar_url": "https://avatars.githubusercontent.com/u/79306200?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Perin-Mangukiya",
  "html_url": "https://github.com/Perin-Mangukiya",
  "followers_url": "https://api.github.com/users/Perin-Mangukiya/followers",
  "following_url": "https://api.github.com/users/Perin-Mangukiya/following{/other_user}",
  "gists_url": "https://api.github.com/users/Perin-Mangukiya/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Perin-Mangukiya/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Perin-Mangukiya/subscriptions",
  "organizations_url": "https://api.github.com/users/Perin-Mangukiya/orgs",
  "repos_url": "https://api.github.com/users/Perin-Mangukiya/repos",
  "events_url": "https://api.github.com/users/Perin-Mangukiya/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Perin-Mangukiya/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Perin Mangukiya",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 3,
  "following": 3,
  "created_at": "2021-02-19T08:38:41Z",
  "updated_at": "2023-03-23T12:41:18Z"
  }