export default [
  {
  "login": "jenishdesai",
  "id": 71323473,
  "node_id": "MDQ6VXNlcjcxMzIzNDcz",
  "avatar_url": "https://avatars.githubusercontent.com/u/71323473?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jenishdesai",
  "html_url": "https://github.com/jenishdesai",
  "followers_url": "https://api.github.com/users/jenishdesai/followers",
  "following_url": "https://api.github.com/users/jenishdesai/following{/other_user}",
  "gists_url": "https://api.github.com/users/jenishdesai/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jenishdesai/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jenishdesai/subscriptions",
  "organizations_url": "https://api.github.com/users/jenishdesai/orgs",
  "repos_url": "https://api.github.com/users/jenishdesai/repos",
  "events_url": "https://api.github.com/users/jenishdesai/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jenishdesai/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "Prafulla-85",
  "id": 75845481,
  "node_id": "MDQ6VXNlcjc1ODQ1NDgx",
  "avatar_url": "https://avatars.githubusercontent.com/u/75845481?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Prafulla-85",
  "html_url": "https://github.com/Prafulla-85",
  "followers_url": "https://api.github.com/users/Prafulla-85/followers",
  "following_url": "https://api.github.com/users/Prafulla-85/following{/other_user}",
  "gists_url": "https://api.github.com/users/Prafulla-85/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Prafulla-85/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Prafulla-85/subscriptions",
  "organizations_url": "https://api.github.com/users/Prafulla-85/orgs",
  "repos_url": "https://api.github.com/users/Prafulla-85/repos",
  "events_url": "https://api.github.com/users/Prafulla-85/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Prafulla-85/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "prashant-pixel",
  "id": 76446251,
  "node_id": "MDQ6VXNlcjc2NDQ2MjUx",
  "avatar_url": "https://avatars.githubusercontent.com/u/76446251?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/prashant-pixel",
  "html_url": "https://github.com/prashant-pixel",
  "followers_url": "https://api.github.com/users/prashant-pixel/followers",
  "following_url": "https://api.github.com/users/prashant-pixel/following{/other_user}",
  "gists_url": "https://api.github.com/users/prashant-pixel/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/prashant-pixel/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/prashant-pixel/subscriptions",
  "organizations_url": "https://api.github.com/users/prashant-pixel/orgs",
  "repos_url": "https://api.github.com/users/prashant-pixel/repos",
  "events_url": "https://api.github.com/users/prashant-pixel/events{/privacy}",
  "received_events_url": "https://api.github.com/users/prashant-pixel/received_events",
  "type": "User",
  "site_admin": false
  }
  ]